/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "fixed_count.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Message1, Message1, AUTO)


PB_BIND(Message2, Message2, AUTO)


PB_BIND(Message3, Message3, AUTO)


PB_BIND(SubMessage, SubMessage, AUTO)


PB_BIND(Message4, Message4, AUTO)



