/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "dmessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Datapoint, Datapoint, AUTO)


PB_BIND(leshiBTmeshDeviceMsg, leshiBTmeshDeviceMsg, 2)


PB_BIND(btActionMsg, btActionMsg, AUTO)


PB_BIND(Gatewayinfo, Gatewayinfo, AUTO)


PB_BIND(GatewayOta, GatewayOta, AUTO)


PB_BIND(combineMsg, combineMsg, AUTO)


PB_BIND(commonMessage, commonMessage, 4)






