/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "dmessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(direction, direction, AUTO)


PB_BIND(type_raw, type_raw, AUTO)


PB_BIND(type_string, type_string, AUTO)


PB_BIND(Datapoint, Datapoint, AUTO)


PB_BIND(leshiBTmeshGWMsg, leshiBTmeshGWMsg, 2)


PB_BIND(Gatewayinfo, Gatewayinfo, AUTO)


PB_BIND(GatewayOta, GatewayOta, AUTO)


PB_BIND(combineMsg, combineMsg, 2)


PB_BIND(commonMessage, commonMessage, 2)







