/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_DMESSAGE_PB_H_INCLUDED
#define PB_DMESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _leshiBTmeshGWMsg { /* device id sub device id */
    char deviceName[128]; /* device name */
    int32_t eleCata; /* derive from cloud server */
    char devicePid[128]; /* device pid */
} leshiBTmeshGWMsg;

/* main page push and pop message */
typedef struct _combineMsg {
    uint32_t index; /* ordinal of item */
    pb_size_t which_item;
    union {
        struct _leshiBTmeshGWMsg *lsBTmeshGW_device;
    } item;
} combineMsg;

typedef struct _commonMessage {
    char *deviceName; /* repeated combineMsg combo=11; */
    uint32_t combo_size;
} commonMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define leshiBTmeshGWMsg_init_default            {"", 0, ""}
#define combineMsg_init_default                  {0, 0, {NULL}}
#define commonMessage_init_default               {NULL, 0}
#define leshiBTmeshGWMsg_init_zero               {"", 0, ""}
#define combineMsg_init_zero                     {0, 0, {NULL}}
#define commonMessage_init_zero                  {NULL, 0}

/* Field tags (for use in manual encoding/decoding) */
#define leshiBTmeshGWMsg_deviceName_tag          3
#define leshiBTmeshGWMsg_eleCata_tag             4
#define leshiBTmeshGWMsg_devicePid_tag           5
#define combineMsg_index_tag                     1
#define combineMsg_lsBTmeshGW_device_tag         2
#define commonMessage_deviceName_tag             3
#define commonMessage_combo_size_tag             10

/* Struct field encoding specification for nanopb */
#define leshiBTmeshGWMsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   deviceName,        3) \
X(a, STATIC,   REQUIRED, INT32,    eleCata,           4) \
X(a, STATIC,   REQUIRED, STRING,   devicePid,         5)
#define leshiBTmeshGWMsg_CALLBACK NULL
#define leshiBTmeshGWMsg_DEFAULT NULL

#define combineMsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   index,             1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (item,lsBTmeshGW_device,item.lsBTmeshGW_device),   2)
#define combineMsg_CALLBACK NULL
#define combineMsg_DEFAULT NULL
#define combineMsg_item_lsBTmeshGW_device_MSGTYPE leshiBTmeshGWMsg

#define commonMessage_FIELDLIST(X, a) \
X(a, POINTER,  REQUIRED, STRING,   deviceName,        3) \
X(a, STATIC,   REQUIRED, UINT32,   combo_size,       10)
#define commonMessage_CALLBACK NULL
#define commonMessage_DEFAULT NULL

extern const pb_msgdesc_t leshiBTmeshGWMsg_msg;
extern const pb_msgdesc_t combineMsg_msg;
extern const pb_msgdesc_t commonMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define leshiBTmeshGWMsg_fields &leshiBTmeshGWMsg_msg
#define combineMsg_fields &combineMsg_msg
#define commonMessage_fields &commonMessage_msg

/* Maximum encoded size of messages (where known) */
/* combineMsg_size depends on runtime parameters */
/* commonMessage_size depends on runtime parameters */
#define leshiBTmeshGWMsg_size                    271

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
