/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "dmessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(leshiBTmeshGWMsg, leshiBTmeshGWMsg, 2)


PB_BIND(combineMsg, combineMsg, AUTO)


PB_BIND(commonMessage, commonMessage, AUTO)



