/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

#ifndef PROTOBUF_C_test_2eproto__INCLUDED
#define PROTOBUF_C_test_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct StudentMsg StudentMsg;
typedef struct SearchRequest SearchRequest;
typedef struct SearchResponse SearchResponse;
typedef struct SearchResponse__Result SearchResponse__Result;
typedef struct SomeOtherMessage SomeOtherMessage;
typedef struct Outer Outer;
typedef struct Outer__MiddleAA Outer__MiddleAA;
typedef struct Outer__MiddleAA__Inner Outer__MiddleAA__Inner;
typedef struct Outer__MiddleBB Outer__MiddleBB;
typedef struct Outer__MiddleBB__Inner Outer__MiddleBB__Inner;


/* --- enums --- */

typedef enum _SearchRequest__Corpus {
  /*
   * option allow_alias = true;
   */
  SEARCH_REQUEST__CORPUS__UNIVERSAL = 0,
  SEARCH_REQUEST__CORPUS__WEB = 1,
  SEARCH_REQUEST__CORPUS__IMAGES = 2,
  SEARCH_REQUEST__CORPUS__LOCAL = 3,
  SEARCH_REQUEST__CORPUS__NEWS = 4,
  SEARCH_REQUEST__CORPUS__PRODUCTDS = 5,
  SEARCH_REQUEST__CORPUS__VIDEO = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SEARCH_REQUEST__CORPUS)
} SearchRequest__Corpus;

/* --- messages --- */

struct  StudentMsg
{
  ProtobufCMessage base;
  char *name;
  uint32_t age;
  uint32_t class_num;
  char *address;
};
#define STUDENT_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&student_msg__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string }


struct  SearchRequest
{
  ProtobufCMessage base;
  char *query;
  int32_t page_number;
  int32_t result_per_page;
  SearchRequest__Corpus corpus;
};
#define SEARCH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&search_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, SEARCH_REQUEST__CORPUS__UNIVERSAL }


struct  SearchResponse__Result
{
  ProtobufCMessage base;
  char *url;
  char *title;
  int32_t page_number;
  size_t n_snippet;
  char **snippet;
};
#define SEARCH_RESPONSE__RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&search_response__result__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0,NULL }


struct  SearchResponse
{
  ProtobufCMessage base;
  size_t n_results;
  SearchResponse__Result **results;
};
#define SEARCH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&search_response__descriptor) \
    , 0,NULL }


struct  SomeOtherMessage
{
  ProtobufCMessage base;
  SearchResponse__Result *results;
};
#define SOME_OTHER_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&some_other_message__descriptor) \
    , NULL }


struct  Outer__MiddleAA__Inner
{
  ProtobufCMessage base;
  int64_t ival;
  protobuf_c_boolean booly;
};
#define OUTER__MIDDLE_AA__INNER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&outer__middle_aa__inner__descriptor) \
    , 0, 0 }


struct  Outer__MiddleAA
{
  ProtobufCMessage base;
};
#define OUTER__MIDDLE_AA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&outer__middle_aa__descriptor) \
     }


struct  Outer__MiddleBB__Inner
{
  ProtobufCMessage base;
  int32_t ival;
  protobuf_c_boolean booly;
};
#define OUTER__MIDDLE_BB__INNER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&outer__middle_bb__inner__descriptor) \
    , 0, 0 }


struct  Outer__MiddleBB
{
  ProtobufCMessage base;
};
#define OUTER__MIDDLE_BB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&outer__middle_bb__descriptor) \
     }


/*
 *深度嵌套
 */
struct  Outer
{
  ProtobufCMessage base;
};
#define OUTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&outer__descriptor) \
     }


/* StudentMsg methods */
void   student_msg__init
                     (StudentMsg         *message);
size_t student_msg__get_packed_size
                     (const StudentMsg   *message);
size_t student_msg__pack
                     (const StudentMsg   *message,
                      uint8_t             *out);
size_t student_msg__pack_to_buffer
                     (const StudentMsg   *message,
                      ProtobufCBuffer     *buffer);
StudentMsg *
       student_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   student_msg__free_unpacked
                     (StudentMsg *message,
                      ProtobufCAllocator *allocator);
/* SearchRequest methods */
void   search_request__init
                     (SearchRequest         *message);
size_t search_request__get_packed_size
                     (const SearchRequest   *message);
size_t search_request__pack
                     (const SearchRequest   *message,
                      uint8_t             *out);
size_t search_request__pack_to_buffer
                     (const SearchRequest   *message,
                      ProtobufCBuffer     *buffer);
SearchRequest *
       search_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   search_request__free_unpacked
                     (SearchRequest *message,
                      ProtobufCAllocator *allocator);
/* SearchResponse__Result methods */
void   search_response__result__init
                     (SearchResponse__Result         *message);
/* SearchResponse methods */
void   search_response__init
                     (SearchResponse         *message);
size_t search_response__get_packed_size
                     (const SearchResponse   *message);
size_t search_response__pack
                     (const SearchResponse   *message,
                      uint8_t             *out);
size_t search_response__pack_to_buffer
                     (const SearchResponse   *message,
                      ProtobufCBuffer     *buffer);
SearchResponse *
       search_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   search_response__free_unpacked
                     (SearchResponse *message,
                      ProtobufCAllocator *allocator);
/* SomeOtherMessage methods */
void   some_other_message__init
                     (SomeOtherMessage         *message);
size_t some_other_message__get_packed_size
                     (const SomeOtherMessage   *message);
size_t some_other_message__pack
                     (const SomeOtherMessage   *message,
                      uint8_t             *out);
size_t some_other_message__pack_to_buffer
                     (const SomeOtherMessage   *message,
                      ProtobufCBuffer     *buffer);
SomeOtherMessage *
       some_other_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   some_other_message__free_unpacked
                     (SomeOtherMessage *message,
                      ProtobufCAllocator *allocator);
/* Outer__MiddleAA__Inner methods */
void   outer__middle_aa__inner__init
                     (Outer__MiddleAA__Inner         *message);
/* Outer__MiddleAA methods */
void   outer__middle_aa__init
                     (Outer__MiddleAA         *message);
/* Outer__MiddleBB__Inner methods */
void   outer__middle_bb__inner__init
                     (Outer__MiddleBB__Inner         *message);
/* Outer__MiddleBB methods */
void   outer__middle_bb__init
                     (Outer__MiddleBB         *message);
/* Outer methods */
void   outer__init
                     (Outer         *message);
size_t outer__get_packed_size
                     (const Outer   *message);
size_t outer__pack
                     (const Outer   *message,
                      uint8_t             *out);
size_t outer__pack_to_buffer
                     (const Outer   *message,
                      ProtobufCBuffer     *buffer);
Outer *
       outer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   outer__free_unpacked
                     (Outer *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*StudentMsg_Closure)
                 (const StudentMsg *message,
                  void *closure_data);
typedef void (*SearchRequest_Closure)
                 (const SearchRequest *message,
                  void *closure_data);
typedef void (*SearchResponse__Result_Closure)
                 (const SearchResponse__Result *message,
                  void *closure_data);
typedef void (*SearchResponse_Closure)
                 (const SearchResponse *message,
                  void *closure_data);
typedef void (*SomeOtherMessage_Closure)
                 (const SomeOtherMessage *message,
                  void *closure_data);
typedef void (*Outer__MiddleAA__Inner_Closure)
                 (const Outer__MiddleAA__Inner *message,
                  void *closure_data);
typedef void (*Outer__MiddleAA_Closure)
                 (const Outer__MiddleAA *message,
                  void *closure_data);
typedef void (*Outer__MiddleBB__Inner_Closure)
                 (const Outer__MiddleBB__Inner *message,
                  void *closure_data);
typedef void (*Outer__MiddleBB_Closure)
                 (const Outer__MiddleBB *message,
                  void *closure_data);
typedef void (*Outer_Closure)
                 (const Outer *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor student_msg__descriptor;
extern const ProtobufCMessageDescriptor search_request__descriptor;
extern const ProtobufCEnumDescriptor    search_request__corpus__descriptor;
extern const ProtobufCMessageDescriptor search_response__descriptor;
extern const ProtobufCMessageDescriptor search_response__result__descriptor;
extern const ProtobufCMessageDescriptor some_other_message__descriptor;
extern const ProtobufCMessageDescriptor outer__descriptor;
extern const ProtobufCMessageDescriptor outer__middle_aa__descriptor;
extern const ProtobufCMessageDescriptor outer__middle_aa__inner__descriptor;
extern const ProtobufCMessageDescriptor outer__middle_bb__descriptor;
extern const ProtobufCMessageDescriptor outer__middle_bb__inner__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_test_2eproto__INCLUDED */
