/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test.pb-c.h"
void   student_msg__init
                     (StudentMsg         *message)
{
  static const StudentMsg init_value = STUDENT_MSG__INIT;
  *message = init_value;
}
size_t student_msg__get_packed_size
                     (const StudentMsg *message)
{
  assert(message->base.descriptor == &student_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t student_msg__pack
                     (const StudentMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &student_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t student_msg__pack_to_buffer
                     (const StudentMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &student_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StudentMsg *
       student_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StudentMsg *)
     protobuf_c_message_unpack (&student_msg__descriptor,
                                allocator, len, data);
}
void   student_msg__free_unpacked
                     (StudentMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &student_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   search_request__init
                     (SearchRequest         *message)
{
  static const SearchRequest init_value = SEARCH_REQUEST__INIT;
  *message = init_value;
}
size_t search_request__get_packed_size
                     (const SearchRequest *message)
{
  assert(message->base.descriptor == &search_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t search_request__pack
                     (const SearchRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &search_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t search_request__pack_to_buffer
                     (const SearchRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &search_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SearchRequest *
       search_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SearchRequest *)
     protobuf_c_message_unpack (&search_request__descriptor,
                                allocator, len, data);
}
void   search_request__free_unpacked
                     (SearchRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &search_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   search_response__result__init
                     (SearchResponse__Result         *message)
{
  static const SearchResponse__Result init_value = SEARCH_RESPONSE__RESULT__INIT;
  *message = init_value;
}
void   search_response__init
                     (SearchResponse         *message)
{
  static const SearchResponse init_value = SEARCH_RESPONSE__INIT;
  *message = init_value;
}
size_t search_response__get_packed_size
                     (const SearchResponse *message)
{
  assert(message->base.descriptor == &search_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t search_response__pack
                     (const SearchResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &search_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t search_response__pack_to_buffer
                     (const SearchResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &search_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SearchResponse *
       search_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SearchResponse *)
     protobuf_c_message_unpack (&search_response__descriptor,
                                allocator, len, data);
}
void   search_response__free_unpacked
                     (SearchResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &search_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   some_other_message__init
                     (SomeOtherMessage         *message)
{
  static const SomeOtherMessage init_value = SOME_OTHER_MESSAGE__INIT;
  *message = init_value;
}
size_t some_other_message__get_packed_size
                     (const SomeOtherMessage *message)
{
  assert(message->base.descriptor == &some_other_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t some_other_message__pack
                     (const SomeOtherMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &some_other_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t some_other_message__pack_to_buffer
                     (const SomeOtherMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &some_other_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SomeOtherMessage *
       some_other_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SomeOtherMessage *)
     protobuf_c_message_unpack (&some_other_message__descriptor,
                                allocator, len, data);
}
void   some_other_message__free_unpacked
                     (SomeOtherMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &some_other_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   outer__middle_aa__inner__init
                     (Outer__MiddleAA__Inner         *message)
{
  static const Outer__MiddleAA__Inner init_value = OUTER__MIDDLE_AA__INNER__INIT;
  *message = init_value;
}
void   outer__middle_aa__init
                     (Outer__MiddleAA         *message)
{
  static const Outer__MiddleAA init_value = OUTER__MIDDLE_AA__INIT;
  *message = init_value;
}
void   outer__middle_bb__inner__init
                     (Outer__MiddleBB__Inner         *message)
{
  static const Outer__MiddleBB__Inner init_value = OUTER__MIDDLE_BB__INNER__INIT;
  *message = init_value;
}
void   outer__middle_bb__init
                     (Outer__MiddleBB         *message)
{
  static const Outer__MiddleBB init_value = OUTER__MIDDLE_BB__INIT;
  *message = init_value;
}
void   outer__init
                     (Outer         *message)
{
  static const Outer init_value = OUTER__INIT;
  *message = init_value;
}
size_t outer__get_packed_size
                     (const Outer *message)
{
  assert(message->base.descriptor == &outer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t outer__pack
                     (const Outer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &outer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t outer__pack_to_buffer
                     (const Outer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &outer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Outer *
       outer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Outer *)
     protobuf_c_message_unpack (&outer__descriptor,
                                allocator, len, data);
}
void   outer__free_unpacked
                     (Outer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &outer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor student_msg__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StudentMsg, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "age",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StudentMsg, age),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class_num",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StudentMsg, class_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StudentMsg, address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned student_msg__field_indices_by_name[] = {
  3,   /* field[3] = address */
  1,   /* field[1] = age */
  2,   /* field[2] = class_num */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange student_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor student_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StudentMsg",
  "StudentMsg",
  "StudentMsg",
  "",
  sizeof(StudentMsg),
  4,
  student_msg__field_descriptors,
  student_msg__field_indices_by_name,
  1,  student_msg__number_ranges,
  (ProtobufCMessageInit) student_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue search_request__corpus__enum_values_by_number[7] =
{
  { "UNIVERSAL", "SEARCH_REQUEST__CORPUS__UNIVERSAL", 0 },
  { "WEB", "SEARCH_REQUEST__CORPUS__WEB", 1 },
  { "IMAGES", "SEARCH_REQUEST__CORPUS__IMAGES", 2 },
  { "LOCAL", "SEARCH_REQUEST__CORPUS__LOCAL", 3 },
  { "NEWS", "SEARCH_REQUEST__CORPUS__NEWS", 4 },
  { "PRODUCTDS", "SEARCH_REQUEST__CORPUS__PRODUCTDS", 5 },
  { "VIDEO", "SEARCH_REQUEST__CORPUS__VIDEO", 6 },
};
static const ProtobufCIntRange search_request__corpus__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex search_request__corpus__enum_values_by_name[7] =
{
  { "IMAGES", 2 },
  { "LOCAL", 3 },
  { "NEWS", 4 },
  { "PRODUCTDS", 5 },
  { "UNIVERSAL", 0 },
  { "VIDEO", 6 },
  { "WEB", 1 },
};
const ProtobufCEnumDescriptor search_request__corpus__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SearchRequest.Corpus",
  "Corpus",
  "SearchRequest__Corpus",
  "",
  7,
  search_request__corpus__enum_values_by_number,
  7,
  search_request__corpus__enum_values_by_name,
  1,
  search_request__corpus__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor search_request__field_descriptors[4] =
{
  {
    "query",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SearchRequest, query),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_number",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SearchRequest, page_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result_per_page",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SearchRequest, result_per_page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "corpus",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SearchRequest, corpus),
    &search_request__corpus__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned search_request__field_indices_by_name[] = {
  3,   /* field[3] = corpus */
  1,   /* field[1] = page_number */
  0,   /* field[0] = query */
  2,   /* field[2] = result_per_page */
};
static const ProtobufCIntRange search_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor search_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SearchRequest",
  "SearchRequest",
  "SearchRequest",
  "",
  sizeof(SearchRequest),
  4,
  search_request__field_descriptors,
  search_request__field_indices_by_name,
  1,  search_request__number_ranges,
  (ProtobufCMessageInit) search_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor search_response__result__field_descriptors[4] =
{
  {
    "url",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SearchResponse__Result, url),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "title",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SearchResponse__Result, title),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_number",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SearchResponse__Result, page_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "snippet",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SearchResponse__Result, n_snippet),
    offsetof(SearchResponse__Result, snippet),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned search_response__result__field_indices_by_name[] = {
  2,   /* field[2] = page_number */
  3,   /* field[3] = snippet */
  1,   /* field[1] = title */
  0,   /* field[0] = url */
};
static const ProtobufCIntRange search_response__result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor search_response__result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SearchResponse.Result",
  "Result",
  "SearchResponse__Result",
  "",
  sizeof(SearchResponse__Result),
  4,
  search_response__result__field_descriptors,
  search_response__result__field_indices_by_name,
  1,  search_response__result__number_ranges,
  (ProtobufCMessageInit) search_response__result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor search_response__field_descriptors[1] =
{
  {
    "results",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SearchResponse, n_results),
    offsetof(SearchResponse, results),
    &search_response__result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned search_response__field_indices_by_name[] = {
  0,   /* field[0] = results */
};
static const ProtobufCIntRange search_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor search_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SearchResponse",
  "SearchResponse",
  "SearchResponse",
  "",
  sizeof(SearchResponse),
  1,
  search_response__field_descriptors,
  search_response__field_indices_by_name,
  1,  search_response__number_ranges,
  (ProtobufCMessageInit) search_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor some_other_message__field_descriptors[1] =
{
  {
    "results",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SomeOtherMessage, results),
    &search_response__result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned some_other_message__field_indices_by_name[] = {
  0,   /* field[0] = results */
};
static const ProtobufCIntRange some_other_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor some_other_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SomeOtherMessage",
  "SomeOtherMessage",
  "SomeOtherMessage",
  "",
  sizeof(SomeOtherMessage),
  1,
  some_other_message__field_descriptors,
  some_other_message__field_indices_by_name,
  1,  some_other_message__number_ranges,
  (ProtobufCMessageInit) some_other_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor outer__middle_aa__inner__field_descriptors[2] =
{
  {
    "ival",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Outer__MiddleAA__Inner, ival),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "booly",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Outer__MiddleAA__Inner, booly),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned outer__middle_aa__inner__field_indices_by_name[] = {
  1,   /* field[1] = booly */
  0,   /* field[0] = ival */
};
static const ProtobufCIntRange outer__middle_aa__inner__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor outer__middle_aa__inner__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Outer.MiddleAA.Inner",
  "Inner",
  "Outer__MiddleAA__Inner",
  "",
  sizeof(Outer__MiddleAA__Inner),
  2,
  outer__middle_aa__inner__field_descriptors,
  outer__middle_aa__inner__field_indices_by_name,
  1,  outer__middle_aa__inner__number_ranges,
  (ProtobufCMessageInit) outer__middle_aa__inner__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define outer__middle_aa__field_descriptors NULL
#define outer__middle_aa__field_indices_by_name NULL
#define outer__middle_aa__number_ranges NULL
const ProtobufCMessageDescriptor outer__middle_aa__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Outer.MiddleAA",
  "MiddleAA",
  "Outer__MiddleAA",
  "",
  sizeof(Outer__MiddleAA),
  0,
  outer__middle_aa__field_descriptors,
  outer__middle_aa__field_indices_by_name,
  0,  outer__middle_aa__number_ranges,
  (ProtobufCMessageInit) outer__middle_aa__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor outer__middle_bb__inner__field_descriptors[2] =
{
  {
    "ival",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Outer__MiddleBB__Inner, ival),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "booly",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Outer__MiddleBB__Inner, booly),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned outer__middle_bb__inner__field_indices_by_name[] = {
  1,   /* field[1] = booly */
  0,   /* field[0] = ival */
};
static const ProtobufCIntRange outer__middle_bb__inner__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor outer__middle_bb__inner__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Outer.MiddleBB.Inner",
  "Inner",
  "Outer__MiddleBB__Inner",
  "",
  sizeof(Outer__MiddleBB__Inner),
  2,
  outer__middle_bb__inner__field_descriptors,
  outer__middle_bb__inner__field_indices_by_name,
  1,  outer__middle_bb__inner__number_ranges,
  (ProtobufCMessageInit) outer__middle_bb__inner__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define outer__middle_bb__field_descriptors NULL
#define outer__middle_bb__field_indices_by_name NULL
#define outer__middle_bb__number_ranges NULL
const ProtobufCMessageDescriptor outer__middle_bb__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Outer.MiddleBB",
  "MiddleBB",
  "Outer__MiddleBB",
  "",
  sizeof(Outer__MiddleBB),
  0,
  outer__middle_bb__field_descriptors,
  outer__middle_bb__field_indices_by_name,
  0,  outer__middle_bb__number_ranges,
  (ProtobufCMessageInit) outer__middle_bb__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define outer__field_descriptors NULL
#define outer__field_indices_by_name NULL
#define outer__number_ranges NULL
const ProtobufCMessageDescriptor outer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Outer",
  "Outer",
  "Outer",
  "",
  sizeof(Outer),
  0,
  outer__field_descriptors,
  outer__field_indices_by_name,
  0,  outer__number_ranges,
  (ProtobufCMessageInit) outer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
